# Generated by Django 5.0.4 on 2024-05-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_employee_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.BooleanField(default=True),
        ),
    ]
