# Generated by Django 5.0.4 on 2024-05-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userprofile_company_name_and_more'),
        ('employee', '0003_employee_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_side',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userprofile'),
        ),
    ]
