# Generated by Django 5.0.4 on 2024-04-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_month', models.DateField()),
                ('monthly_income', models.DecimalField(decimal_places=0, max_digits=10)),
                ('monthly_expenses', models.DecimalField(decimal_places=0, max_digits=10)),
                ('current_month_balance', models.DecimalField(decimal_places=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('salary_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryinformation')),
            ],
        ),
    ]
