# Generated by Django 5.0.4 on 2024-04-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_paymenthistory_paymend_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='paymend_time',
            new_name='payment_time',
        ),
    ]
