# Generated by Django 3.2.4 on 2023-12-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='hire_date',
            new_name='date_of_hire',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='username', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='WorkTime',
        ),
    ]
