# Generated by Django 3.2.4 on 2023-12-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0002_auto_20231223_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
