# Generated by Django 3.2.4 on 2024-01-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0005_auto_20231231_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='num_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('married', 'married'), ('Single', 'Single')], max_length=20),
        ),
    ]
