# Generated by Django 3.2.4 on 2024-01-12 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0007_auto_20240112_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
