# Generated by Django 3.2.4 on 2024-01-12 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getsalari', '0008_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companey_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('hourly_salary', models.IntegerField(default=241286)),
                ('overtime_salary', models.IntegerField(default=337800)),
                ('the_right_of_the_child', models.IntegerField(default=5308284)),
                ('ben_kargari', models.IntegerField(default=10795000)),
                ('right_to_housing', models.IntegerField(default=8255000)),
                ('base_years', models.IntegerField(default=2100000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
