# Generated by Django 3.2.4 on 2024-01-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('hire_date', models.DateField()),
                ('employment_status', models.BooleanField(default=False)),
                ('num_children', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
