# Generated by Django 3.2.4 on 2024-01-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0012_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
