# Generated by Django 3.2.4 on 2024-01-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0013_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='num_children',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='SalaryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.DateField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_month_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getsalari.employee')),
            ],
            options={
                'unique_together': {('employee', 'salary_month')},
            },
        ),
    ]
