# Generated by Django 5.0.4 on 2024-04-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0015_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='companey_name',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='base_years',
            field=models.DecimalField(decimal_places=2, default=2100000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ben_kargari',
            field=models.DecimalField(decimal_places=2, default=10795000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hourly_salary',
            field=models.DecimalField(decimal_places=2, default=241286, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='overtime_salary',
            field=models.DecimalField(decimal_places=2, default=337800, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='right_to_housing',
            field=models.DecimalField(decimal_places=2, default=8255000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='the_right_of_the_child',
            field=models.DecimalField(decimal_places=2, default=5308284, max_digits=10),
        ),
    ]
