# Generated by Django 5.0.4 on 2024-04-21 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0016_rename_companey_name_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salaryinformation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='salaryinformation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
