# Generated by Django 5.0.4 on 2024-04-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0017_alter_salaryinformation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryinformation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
