# Generated by Django 5.0.4 on 2024-04-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0020_paymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryinformation',
            name='total_payments',
        ),
    ]
