# Generated by Django 5.0.4 on 2024-04-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0021_remove_salaryinformation_total_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salaryinformation',
            name='current_month_balance',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryinformation',
            name='monthly_expenses',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryinformation',
            name='monthly_income',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='base_years',
            field=models.DecimalField(decimal_places=0, default=2100000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ben_kargari',
            field=models.DecimalField(decimal_places=0, default=10795000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hourly_salary',
            field=models.DecimalField(decimal_places=0, default=241286, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='overtime_salary',
            field=models.DecimalField(decimal_places=0, default=337800, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='right_to_housing',
            field=models.DecimalField(decimal_places=0, default=8255000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='the_right_of_the_child',
            field=models.DecimalField(decimal_places=0, default=5308284, max_digits=10),
        ),
    ]
