# Generated by Django 5.0.4 on 2024-04-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0023_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryinformation',
            name='employee',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
        migrations.DeleteModel(
            name='SalaryInformation',
        ),
    ]
