# Generated by Django 5.0.4 on 2024-04-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getsalari', '0024_remove_salaryinformation_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
